### ISSUE TITLE
getting the exception in rVRC project 

### ISSUE THREAD

**Issue by jayskhatri** [jayskhatri/algo-implementation#1]
rVRC is receiver side vertical redundancy check program.

OUTPUT:
Message received Successfully
```
Exception in thread "main" java.lang.NumberFormatException: For input string: "1101000"
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at rvrc.RVRC.numToChar(RVRC.java:66)
	at rvrc.RVRC.main(RVRC.java:54)
C:\Users\Jay S Khatri\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java
``` returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by ashokkumarta** [comment]
Hi, I am checking this. Will send you the details if I find a fix.

**Comment by ashokkumarta** [comment]
Issue is due to adding backspace character to remove the last character. It only adds the backspace character at the end of the string, hence the number format exception. We can use substring to remove the last character instead.

Have the fixed code. But guess I don't have permission on this repo to create a branch and check it in

**Comment by jayskhatri** [comment]
You can fork this repo then do the changes... Then you can create pull request.

**Comment by jayskhatri** [comment]
@ashokkumarta You can fork this repo then do the changes... Then you can create pull request.

**Comment by ashokkumarta** [comment]
Yes. Have done that and raised a pull request. Pls. check.

**Comment by jayskhatri** [comment]
Thanks merged pull request.

**Comment by jayskhatri** [comment]
@ashokkumarta  thanks, merged pull request.
